// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_classificacao from "./routes/api/classificacao.ts";
import * as $api_ranking from "./routes/api/ranking.ts";
import * as $api_update from "./routes/api/update.ts";
import * as $index from "./routes/index.tsx";
import * as $Ranking from "./islands/Ranking.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/classificacao.ts": $api_classificacao,
    "./routes/api/ranking.ts": $api_ranking,
    "./routes/api/update.ts": $api_update,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Ranking.tsx": $Ranking,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
